package com.victor.sistema;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class Conexion extends javax.swing.JInternalFrame {
    
    Connection conexion =null;
    public  static   String url = " "; 
    public  static   String usuario = " ";
    public  static   String contrasenha = " ";
    public  static final String driver = "com.mysql.cj.jdbc.Driver";
    

    
    public Conexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bConectarse = new javax.swing.JButton();
        lTextUsu = new javax.swing.JTextField();
        lTextContra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        bConectarse.setText("Conectar");
        bConectarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectarseActionPerformed(evt);
            }
        });

        lTextUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lTextUsuActionPerformed(evt);
            }
        });

        lTextContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lTextContraActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTextContra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTextUsu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(bConectarse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lTextUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lTextContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(bConectarse)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConectarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConectarseActionPerformed
        Connection conexion=getConnection( );
    }//GEN-LAST:event_bConectarseActionPerformed

    private void lTextContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lTextContraActionPerformed
        lTextContra.getText();
    }//GEN-LAST:event_lTextContraActionPerformed

    private void lTextUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lTextUsuActionPerformed
        lTextUsu.getText();
    }//GEN-LAST:event_lTextUsuActionPerformed

    
    
    public Connection getConnection(   ){
    Connection conexion=null;
       url ="jdbc:mysql://localhost:3306/programacionbd?autoReconnet=true&useSSL=false";
       //usuario =lTextUsu.getText();
       //contrasenha=lTextContra.getText();
       usuario ="root";
       contrasenha="1234";
       
       
  
        try{

            Class.forName(driver);
            conexion=(Connection) DriverManager.getConnection(url,usuario,contrasenha);
            JOptionPane.showMessageDialog(null,"Conexion establecida!!!");

    }catch(Exception ex){
        System.err.println("Error, "+ex);

    }
       
    return conexion;
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConectarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField lTextContra;
    private javax.swing.JTextField lTextUsu;
    // End of variables declaration//GEN-END:variables
}
