package com.victor.sistema;
import static com.victor.sistema.Conexion.contrasenha;
import static com.victor.sistema.Conexion.url;
import static com.victor.sistema.Conexion.driver;
import static com.victor.sistema.Conexion.usuario;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victor
 */
public class Modificar extends javax.swing.JInternalFrame {

        Connection conexion = null;
        PreparedStatement ps;
        ResultSet rs;
        
    public Modificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        bModificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lgmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bHombre = new javax.swing.JRadioButton();
        lDNI = new javax.swing.JTextField();
        bMujer = new javax.swing.JRadioButton();
        lNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        lApellidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Actualizar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();

        jLabel3.setText("Nombre");

        bModificar.setText("MODIFICAR");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        jLabel4.setText("Apellidos");

        jLabel5.setText("Fecha de nacimiento");

        jLabel6.setText("Sexo");

        jLabel7.setText("gmail");

        lgmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgmailActionPerformed(evt);
            }
        });

        jLabel1.setText("Modificación de Clientes");

        bHombre.setText("Hombre");

        bMujer.setText("Mujer");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "DNI", "Sexo", "Fecha", "Gmail"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        jLabel2.setText("DNI");

        Actualizar.setText("ACTUALIZAR");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        bBuscar.setText("BUSCAR");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(lNombre)
                            .addComponent(lApellidos)
                            .addComponent(lgmail)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bMujer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bHombre)
                                .addGap(17, 17, 17))
                            .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bBuscar)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5))
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bMujer)
                    .addComponent(bHombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lgmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 126, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        int anho=fecha.getCalendar().get(Calendar.YEAR);
        int mes=fecha.getCalendar().get(Calendar.MONTH);
        int dia=fecha.getCalendar().get(Calendar.DAY_OF_MONTH);

        Date fecha=Date.valueOf(anho+"-"+mes+"-"+dia);

        String sexo="G";

        if(bHombre.isSelected()){
            sexo="Masculino";
        }if(bMujer.isSelected()){
            sexo="Femenino";
        }

        try {
            conexion=getConnection( );
            ps= conexion.prepareStatement("UPDATE clientes SET Dni ='"+lDNI.getText()+"',Nombre ='"+lNombre.getText()+"',Apellidos ='"+lApellidos.getText()+"',Fecha ='"+fecha+"',Sexo ='"+sexo+"',Gmail ='"+lgmail.getText()+"' where Dni ='"+lDNI.getText()+"'");
            
            int resultado= ps.executeUpdate();

            if(resultado>0){
                JOptionPane.showMessageDialog(null,"Modificado correctamente");
            }else{
                JOptionPane.showMessageDialog(null,"Error al modificar");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }

    }//GEN-LAST:event_bModificarActionPerformed

    private void lgmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgmailActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        DefaultTableModel modelotabla = new DefaultTableModel();
        tabla.setModel(modelotabla);

        try {
            conexion=getConnection( );

            ps= conexion.prepareStatement("select * from clientes");
             
            rs= ps.executeQuery();

            modelotabla.addColumn("Dni");
            modelotabla.addColumn("Nombre");
            modelotabla.addColumn("Apellidos");
            modelotabla.addColumn("Fecha");
            modelotabla.addColumn("Sexo");
            modelotabla.addColumn("Gmail");

            while(rs.next()) {
                Object fila[] =new Object[6];
                for( int i=0; i<6; i++){
                    fila[i]= rs.getObject(i+1);
                }
                modelotabla.addRow(fila);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }

    }//GEN-LAST:event_ActualizarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        
        
        try {
            conexion=getConnection();
            ps=conexion.prepareStatement("select * from clientes where Dni='"+lDNI.getText()+"'");
            
            rs=ps.executeQuery();
                lDNI.setText(""); 
                lNombre.setText(""); 
                lApellidos.setText(""); 
                bHombre.setSelected(false);
                bMujer.setSelected(false);
                lgmail.setText("");
                
            if(rs.next()){
                lDNI.setText(rs.getString("Dni"));
                lNombre.setText(rs.getString("Nombre"));
                lApellidos.setText(rs.getString("Apellidos"));
                fecha.setDate(rs.getDate("fecha"));
                lgmail.setText(rs.getString("Gmail"));
                String a=rs.getString("Sexo");
                  
                  if(a.equals("Masculino")){
                 
                    bHombre.setSelected(true);
                   
                  }if(a.equals("Femenino")){
 
                  bMujer.setSelected(true);
                  } 
                  
            }else{
                JOptionPane.showMessageDialog(null,"Persona no encontrada");
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        
    }//GEN-LAST:event_bBuscarActionPerformed

    public Connection getConnection(   ){
     
       url = url;
       usuario = usuario ;    
       contrasenha = contrasenha ;
       
        try{
        Class.forName(driver);
     conexion=(Connection) DriverManager.getConnection(url,usuario,contrasenha);
           
                   
    }catch(Exception ex){
        System.err.println("Error, "+ex);
             
    }
        
    return conexion;
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JRadioButton bHombre;
    private javax.swing.JButton bModificar;
    private javax.swing.JRadioButton bMujer;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lApellidos;
    private javax.swing.JTextField lDNI;
    private javax.swing.JTextField lNombre;
    private javax.swing.JTextField lgmail;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
